server:
  port: 8989   #指定端口号
  context-path: /sb  #指定对应项目名
  jsp-servlet:
    init-parameters:
      development: true          #开启JSP的热部署
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #Druid连接池
    driver-class-name: com.mysql.jdbc.Driver      #Mysql的驱动
    url: jdbc:mysql://localhost:3306/study   #URL
    username: root
    password: root
  mvc:
    view:
      prefix: /                     #视图解析器
      suffix: .jsp
      #修改上传文件大小:
  http:
    multipart:
      max-file-size: 209715200 #单位是字节

mybatis:
  type-aliases-package: com.baizhi.bean   #包中的类起别名
  mapper-locations: classpath:com/baizhi/mapper/*Mapper.xml  #Mapper文件注册
